### ISSUE TITLE
facebook share

### ISSUE THREAD

**Issue by SKI777** [byrobingames/byrobintoolsetmanager#1]
Hi there,

I guess simple share extension needs an update for Stencyl 4.0 build 10240. Facebook share options crash the tests
![ekran resmi 2019-01-23 03 38 56](https://user-images.githubusercontent.com/46684287/51575702-26822f00-1ec4-11e9-8e6e-4fd19993eae3.png)

**Comment by byrobingames** [comment]
You need to activate the Toolset before you run/test you game.
You can activate the Toolset by just clicking on after you opened your game.

Can you confirm if this works?

**Comment by SKI777** [comment]
Hello,

Toolset is enabled, if you are talking about this. Do i have to click on it too? 


Rasim Oskay KOCAOGLU
iPhone'umdan gönderildi

**Comment by byrobingames** [comment]
Every time you open you game, open the Toolset by clicking on it even if its already enabled. This will activitate the Toolset.

**Comment by SKI777** [comment]
Hello Robin,

Sorry for bugging you. I clicked as you described as below.



But still receive this error;



> Robin Schaafsma <notifications@github.com> şunları yazdı (23 Oca 2019 14:19):
> 
>

**Comment by SKI777** [comment]
I just realized it doesnt work on html5.... but it works perfect on ios and android:) if u want i can withdraw my comments. All apologies Robin🙏🏼🙏🏼

Rasim Oskay KOCAOGLU
iPhone'umdan gönderildi

**Comment by byrobingames** [comment]
O ok, Yeah it is only for mobile.

No problem i will close this issue.

**Comment by SKI777** [comment]
Thank you very much for support

Rasim Oskay KOCAOGLU
iPhone'umdan gönderildi
